/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.choibean.android.hangeulize;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int flag=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int taegeuk=0x7f020002;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f070007;
        public static final int LinearLayout02=0x7f07000f;
        public static final int LinearLayout03=0x7f070017;
        public static final int LinearLayout04=0x7f07001c;
        public static final int LinearLayout05=0x7f070020;
        public static final int copyButton=0x7f070005;
        public static final int dubeolshikMenuItem=0x7f070026;
        public static final int helpButton=0x7f070006;
        public static final int helperLabel=0x7f070024;
        public static final int inputEdit=0x7f070002;
        public static final int keyA=0x7f070018;
        public static final int keyB=0x7f07000d;
        public static final int keyBs=0x7f070021;
        public static final int keyCh=0x7f070012;
        public static final int keyD=0x7f07000a;
        public static final int keyEo=0x7f07001a;
        public static final int keyEu=0x7f07001f;
        public static final int keyG=0x7f070008;
        public static final int keyH=0x7f070016;
        public static final int keyJ=0x7f070011;
        public static final int keyK=0x7f070013;
        public static final int keyM=0x7f07000c;
        public static final int keyN=0x7f070009;
        public static final int keyNg=0x7f070010;
        public static final int keyO=0x7f07001d;
        public static final int keyP=0x7f070015;
        public static final int keyR=0x7f07000b;
        public static final int keyS=0x7f07000e;
        public static final int keySp=0x7f070022;
        public static final int keyT=0x7f070014;
        public static final int keyU=0x7f07001e;
        public static final int keyYa=0x7f070019;
        public static final int keyYeo=0x7f07001b;
        public static final int koreanLabel=0x7f070003;
        public static final int modeButton=0x7f070023;
        public static final int notificationMenuItem=0x7f070027;
        public static final int outputClearButton=0x7f070025;
        public static final int outputEdit=0x7f070004;
        public static final int previewButton=0x7f070001;
        public static final int previewLabel=0x7f070000;
    }
    public static final class layout {
        public static final int tall=0x7f030000;
        public static final int wide=0x7f030001;
    }
    public static final class menu {
        public static final int main_menu=0x7f060000;
    }
    public static final class string {
        public static final int app_name=0x7f040003;
        public static final int copied_to_clipboard=0x7f040023;
        public static final int copy=0x7f040008;
        public static final int copy_failed=0x7f040022;
        public static final int dbs_off=0x7f040004;
        public static final int dbs_on=0x7f040005;
        public static final int help=0x7f040009;
        public static final int korean_a=0x7f040019;
        public static final int korean_ba=0x7f040010;
        public static final int korean_bs=0x7f040020;
        public static final int korean_cha=0x7f040014;
        public static final int korean_da=0x7f04000d;
        public static final int korean_eo=0x7f04001b;
        public static final int korean_eu=0x7f04001f;
        public static final int korean_ga=0x7f04000b;
        public static final int korean_ha=0x7f040018;
        public static final int korean_ja=0x7f040013;
        public static final int korean_ka=0x7f040015;
        public static final int korean_label=0x7f04000a;
        public static final int korean_ma=0x7f04000f;
        public static final int korean_na=0x7f04000c;
        public static final int korean_nga=0x7f040012;
        public static final int korean_o=0x7f04001d;
        public static final int korean_pa=0x7f040017;
        public static final int korean_ra=0x7f04000e;
        public static final int korean_sa=0x7f040011;
        public static final int korean_sp=0x7f040021;
        public static final int korean_ta=0x7f040016;
        public static final int korean_u=0x7f04001e;
        public static final int korean_ya=0x7f04001a;
        public static final int korean_yeo=0x7f04001c;
        public static final int notification_motto=0x7f040007;
        public static final int notification_title=0x7f040006;
        public static final int press_space=0x7f040002;
        public static final int type_here1=0x7f040000;
        public static final int type_here2=0x7f040001;
    }
    public static final class style {
        public static final int Theme=0x7f050000;
        public static final int Theme_Translucent=0x7f050001;
    }
}
