/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.choibean.android.hangeulize;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int flag=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int taegeuk=0x7f020002;
        public static final int transparent_background=0x7f020003;
    }
    public static final class id {
        public static final int copyButton=0x7f060006;
        public static final int dubeolshik=0x7f060009;
        public static final int helpButton=0x7f060008;
        public static final int helperLabel=0x7f060002;
        public static final int inputEdit=0x7f060003;
        public static final int koreanLabel=0x7f060004;
        public static final int modeButton=0x7f060007;
        public static final int outputEdit=0x7f060005;
        public static final int previewButton=0x7f060001;
        public static final int previewLabel=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class menu {
        public static final int main_menu=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040003;
        public static final int dbs_off=0x7f040004;
        public static final int dbs_on=0x7f040005;
        public static final int notification_motto=0x7f040007;
        public static final int notification_title=0x7f040006;
        public static final int press_space=0x7f040002;
        public static final int type_here1=0x7f040000;
        public static final int type_here2=0x7f040001;
    }
}
